version: '3'
services:
  tests:
    image: playw_python
    command: ./entrypoint.sh
    depends_on:
      - setup
    volumes:
      - .:/src
    environment:
      - DOCKER_RUN=True
  setup:
    build:
      context: .
      dockerfile: Dockerfile
    image: playw_python